### ISSUE TITLE
Exception thrown with no details for NearBySearch

### ISSUE THREAD

**Issue by StephaneBischoff** [vivet/GoogleApi#166]
The following call fails and the exception does not say much. Seems like the Address does not work for **PlacesNearBySearchRequest**. 
Tried with Longitude and Latitude only and that worked.

```
var request = new PlacesNearBySearchRequest()
            {
                Key = "MY GOOGLE API KEY"
            };
request.Location = new Location() { Address = "456 Some Street, Some City" };
request.Radius = 1000;
var response = await GooglePlaces.NearBySearch.QueryAsync(request, cancellationToken);
```

```
GoogleApi.Exceptions.GoogleApiException: InvalidRequest: 
   at GoogleApi.HttpEngine`2.<>c__DisplayClass2_0.<<QueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at GoogleApi.HttpEngine`2.QueryAsync(TRequest request, CancellationToken cancellationToken)
   at MyApp.Services.PlacesService.ListPlaces(String address, CancellationToken cancellationToken) in \MyApp\MyApp\Services\PlacesService.cs:line 22
   at MyApp.Controllers.PlacesController.Get(CancellationToken cancellationToken) in MyApp\MyApp\Controllers\PlacesController.cs:line 31
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
```

**Comment by vivet** [comment]
Hi
Your address seems strange. Have you tried with a real address? If so, I will try to do some tests. I am in vacation until Monday, but I can take a look when I am back.

**Comment by StephaneBischoff** [comment]
Yes, I did copy paste of the actual address in maps.google.com (The one provided automatically in the search bar).  Thanks, enjoy your vacation. no worries :).

**Comment by vivet** [comment]
Hi
I checked the google places documentation, and it seems you can't use an address string with nearby search, but only a location of latitude, longitude. I will update to remove the incorrect Location.Address for the nearby search request.

**Comment by StephaneBischoff** [comment]
Great. Let me know when the fix is in. Thanks.

**Comment by vivet** [comment]
Well the fix is to remove what you want to do, so just don't use Location.Address, and it will work. Nevertheless, I will deploy an update tomorrow, and let you know.

**Comment by vivet** [comment]
I have published the change. Package should be ready on 5-10 min.
Please star my library, if you like it.

**Comment by vivet** [comment]
Can I close the issue?
