### ISSUE TITLE
DistanceMatrixRequest deserialization problem with NewtonSoft

### ISSUE THREAD

**Issue by GoNextGroup** [vivet/GoogleApi#183]
I know that you are on vacations, so, pls, check this issue when you'll come back.

So, I have 2 gRPC services - one caller, one server. So, I use JSON data format and Newtonsoft for data serialization/deserialization.

So, when I try to pass DistanceMatrixRequest  via JSON, I have a deserialization error.
Here is the JSON serialized data:

```
{
  "$type": "GoogleApi.Entities.Maps.DistanceMatrix.Request.DistanceMatrixRequest, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74",
  "OriginsRaw": null,
  "DestinationsRaw": null,
  "Origins": {
    "$type": "System.Linq.Enumerable+SelectListIterator`2[[EFCoreDataModel.DataClasses.Orders.Order, EFCoreDataModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74]], System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "$values": [
      {
        "$type": "GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74",
        "Latitude": 55.78747999999999,
        "Longitude": 37.66968489999999,
        "Address": "улица Шумкина, 18, Москва, Россия"
      },
      {
        "$type": "GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74",
        "Latitude": 55.78776970000001,
        "Longitude": 37.670614,
        "Address": "улица Шумкина, 19, Москва, Россия"
      }
    ]
  },
  "Destinations": {
    "$type": "System.Linq.Enumerable+SelectListIterator`2[[EFCoreDataModel.DataClasses.Orders.Order, EFCoreDataModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74]], System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "$values": [
      {
        "$type": "GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74",
        "Latitude": 55.672867,
        "Longitude": 37.55827999999997,
        "Address": "улица Профсоюзная, 31, Москва, Россия"
      },
      {
        "$type": "GoogleApi.Entities.Common.Location, GoogleApi, Version=3.9.6.0, Culture=neutral, PublicKeyToken=781851e053b06e74",
        "Latitude": 55.69187299999999,
        "Longitude": 37.60644100000002,
        "Address": "Севастопольский проспект, 2, Москва, Россия"
      }
    ]
  },
  "Units": 0,
  "Avoid": 0,
  "TravelMode": 0,
  "TrafficModel": 0,
  "TransitMode": 15,
  "TransitRoutingPreference": 0,
  "DepartureTime": "2020-01-20T14:18:00.2883229Z",
  "ArrivalTime": null,
  "Language": 8,
  "Channel": null
} 
```

Here is the error:

```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Cannot create and populate list type System.Linq.Enumerable+SelectListIterator`2[EFCoreDataModel.DataClasses.Orders.Order,GoogleApi.Entities.Common.Location]. Path 'Origins.$values', line 7, position 16.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(JTokenReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at WebFoundationClassesCore.ServiceClasses.JsonMarshallerFactory.Deserialize[T](Byte[] payload) in C:\Users\Rebelion\Repos\GoNextGroup\WebFoundationClassesCore\WebFoundationClassesCore\ServiceClasses\JsonMarshallFactory\JsonMarshallerFactory.cs:line 66
   at Grpc.Core.Marshaller`1.EmulateContextualDeserializer(DeserializationContext context)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.<ReadSingleMessageAsync>d__13`1.MoveNext()

  This exception was originally thrown at this call stack:
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonArrayContract, out bool)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, object, string)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(Newtonsoft.Json.Linq.JTokenReader, ref System.Type, ref Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, object, out object, out string)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, object)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, object)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.JsonConverter, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.JsonReader, object)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(object, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, string)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, object)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, object)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, bool)
    ...
    [Call Stack Truncated]
```

What's the reason? 

Thank you.

**Comment by vivet** [comment]
You are trying to create a list, where the type is IEnumerable. I'm not entirely sure what you are doing before you get the error. Show me the code that causes the error. Or use OriginsRaw / DestinationsRaw to have complete control.

**Comment by GoNextGroup** [comment]
Vivet, thank you for your answer. I'll close this issue - it's not an issue itself, because I used `ICollection<Location>` which I get from another gRPC object calling. It's strange, I don't understand why, but when I use `ToList()` after the `Select` expression, It works well.
