### ISSUE TITLE
Business status 'FUTURE_OPENING' is not supported

### ISSUE THREAD

**Issue by marchy** [vivet/GoogleApi#305]
When fetching place details, the client fails with the following error if the status is returned as 'FUTURE_OPENING':
```
GoogleApi.Exceptions.GoogleApiException: Requested value 'FUTURE_OPENING' was not found.
 ---> System.ArgumentException: Requested value 'FUTURE_OPENING' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at GoogleApi.HttpEngine`2.QueryAsync(TRequest request, CancellationToken cancellationToken)
```

### Sample
Place ID: `ChIJ28ASY7a2pBIRQgmgKO2MzYo`
Library invocation:
```
PlacesDetailsResponse placeResponse = await GooglePlaces.Details.QueryAsync( new PlacesDetailsRequest {
	PlaceId = googlePlaceID,
	Key = SecurityOptions.GooglePlacesAPIKey,
});
```
API request:
```
https://maps.googleapis.com/maps/api/place/details/json?key={CLIENT_KEY}&placeid=ChIJ28ASY7a2pBIRQgmgKO2MzYo&language=en&fields=business_status
```
API response:
```
{
	"html_attributions": [],
	"result": {
		"business_status": "FUTURE_OPENING",
		"more_opening_hours": []
	},
	"status": "OK"
}
```

**Comment by dlboutwe** [comment]
Interesting. I don't see any of the google documentation referencing FUTURE_OPENING as an option for that field. I've opened an issue report with Google about it. https://issuetracker.google.com/issues/249164721

**Comment by vivet** [comment]
PR merged, and new NuGet is on the way in 5-10 min
